version: '3.8'
services:
  frontend:
    build:
      context: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build: 
      context: backend/api
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge