# Define player data columns
player_data_columns = [
    'id',
    'web_name',
    'team',
    'element_type',
    'selected_by_percent',
    'now_cost',
    'minutes',
    'transfers_in',
    'value_season',
    'total_points',
    'goals_scored',
    'assists',
    'clean_sheets',
    'goals_conceded',
    'own_goals',
    'penalties_saved',
    'penalties_missed',
    'yellow_cards',
    'red_cards',
    'saves',
    'starts',
    'photo',
    'in_dreamteam',
    'defensive_contribution_per_90'
]
