# Dictionary with main hexcode for each team
team_colour_map = {'Arsenal': '#EF0107',
                   'Aston Villa': '#670E36',
                   'Brentford': '#e30613',
                   'Brighton': '#0057B8',
                   'Burnley': '#6C1D45',
                   'Chelsea': '#034694',
                   'Crystal Palace': '#1B458F',
                   'Everton': '#003399',
                   'Leicester': '#003090',
                   'Leeds': '#FFCD00',
                   'Liverpool': '#C8102E',
                   'Man City': '#6CABDD',
                   'Man Utd': '#DA291C',
                   'Newcastle': '#241F20',
                   'Norwich': '#FFF200',
                   'Southampton': '#D71920',
                   'Spurs': '#FFFFFF',
                   'Watford': '#7A263A',
                   'West Ham': '#7A263A',
                   'Wolves': '#FDB913'
                   }
