name: Build & Push - Streamlit Frontend

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
      - feature/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build & Push Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      - name: Lint with flake8
        run: |
          flake8 frontend --count --show-source --statistics

      - name: Lint with yamllint
        run: |
          yamllint -c .yamllint.yml .github/workflows/build-frontend.yml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build image: ${{ github.repository }}-frontend"
        working-directory: './frontend'
        run: docker build -f Dockerfile -t $REGISTRY/$IMAGE_NAME-frontend .

      - name: Push ${{ github.repository }}-frontend to GitHub container registry
        run: |
          docker push $REGISTRY/$IMAGE_NAME-frontend:latest

      - name: DockerHub Login
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push ${{ github.repository }}-frontend to DockerHub Container registry
        run: |
          docker tag $REGISTRY/$IMAGE_NAME-frontend:latest $IMAGE_NAME-frontend:latest
          docker push $IMAGE_NAME-frontend
