name: Flyway Migration

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/flyway.yml'
      - 'database/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/flyway.yml'
      - 'database/**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: flyway-migration
  cancel-in-progress: false

jobs:
  call-flyway:
    name: Flyway
    uses: powellrhys/powellrhys-iac/.github/workflows/template-migrate-flyway.yml@feature/flyway
    with:
      resource_group: powellrhys-sql-server-rg
      sql_server: powellrhys-sqlserver
      database_path: ./database/flyway
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SQL_SERVER_JDBC_URL: ${{ secrets.SQL_SERVER_JDBC_URL }}
      SQL_SERVER_USERNAME: ${{ secrets.SQL_SERVER_USERNAME }}
      SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
