name: Update Data

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:  
  update-data:
    name: Update Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Collect Runtime IP Address
        shell: push
        run: |
          $agentIP = $(curl -s https://api.ipify.org)
          Write-Host $agentIP

      # - name: Install Microsoft ODBC
      #   run: sudo ACCEPT_EULA=Y apt-get install msodbcsql17 -y

      # - name: Update Data
      #   env:
      #     leagues: ${{ vars.LEAGUES }}
      #     manager_id: ${{ vars.MANAGER_ID }}
      #     sql_server_name: ${{ secrets.SQL_SERVER_NAME }}
      #     sql_server_database: ${{ secrets.SQL_SERVER_DATABASE }}
      #     sql_server_username: ${{ secrets.SQL_SERVER_USERNAME }}
      #     sql_server_password: ${{ secrets.SQL_SERVER_PASSWORD }}
      #   run: python backend/UpdateData/__init__.py
